/**
 * Router Forge parity contract.
 *
 * The nano and embed runtimes here are the TypeScript twins of the Python
 * runtime in the forge (jacky/router_forge.py). `router-fixture-v1.json` is
 * generated by the Python side and carries the exact output it produced for
 * each case, so this file asserts the two implementations agree to four
 * decimal places rather than merely "look similar".
 *
 * This is the test that makes a router artifact portable: an artifact trained
 * on the PC and run on the phone must route identically, or the fleet's
 * behaviour silently differs by device. Do not relax an assertion here to make
 * a change pass — regenerate the fixture on both sides instead.
 */
import { describe, it, expect } from 'vitest';
import fixture from './router-fixture-v1.json';
import { compileNano, normalizeText, fnv1a, utf8Bytes, softmax } from './nanoRuntime';
import { routeWithEmbedding } from './embedRuntime';
import { validateArtifact } from './validate';
import type { EmbedModel, NanoModel, RouteResult } from './types';

interface Case {
  text: string;
  expected: RouteResult;
  queryVector?: number[];
}

const nanoArtifact = fixture.artifacts.nano as unknown as {
  labels: string[];
  model: NanoModel;
};
const embedArtifact = fixture.artifacts.embed as unknown as {
  labels: string[];
  model: EmbedModel;
};
const nanoCases = fixture.cases.nano as unknown as Case[];
const embedCases = fixture.cases.embed as unknown as Case[];

describe('router forge fixture', () => {
  it('is the version this runtime understands', () => {
    // The envelope is 'router-forge-fixture'; the artifacts INSIDE it carry
    // 'router-forge'. Asserting both keeps a fixture from a different
    // generator, or an artifact from a newer forge, from passing quietly.
    expect(fixture.format).toBe('router-forge-fixture');
    expect(fixture.version).toBe(1);
    expect(fixture.artifacts.nano.format).toBe('router-forge');
    expect(fixture.artifacts.embed.format).toBe('router-forge');
  });

  it('carries cases for both runtimes (a truncated fixture must not pass silently)', () => {
    expect(nanoCases.length).toBeGreaterThan(0);
    expect(embedCases.length).toBeGreaterThan(0);
  });
});

describe('nano runtime matches the Python forge exactly', () => {
  const router = compileNano(nanoArtifact.labels, nanoArtifact.model);

  it.each(nanoCases.map((c, i) => [i, c] as const))(
    'case %i routes identically to Python',
    (_i, testCase) => {
      const result = router.route(testCase.text);
      expect(result.label).toBe(testCase.expected.label);
      expect(result.confidence).toBeCloseTo(testCase.expected.confidence, 4);
      for (const [label, score] of Object.entries(testCase.expected.scores)) {
        expect(result.scores[label]).toBeCloseTo(score, 4);
      }
    }
  );
});

describe('embed runtime matches the Python forge exactly', () => {
  it.each(embedCases.map((c, i) => [i, c] as const))(
    'case %i routes identically to Python',
    (_i, testCase) => {
      // Embed cases carry the query vector the Python side used, so this
      // compares the runtime and not whatever embedder happens to be present.
      if (!testCase.queryVector) return;
      const result = routeWithEmbedding(
        embedArtifact.labels,
        embedArtifact.model,
        testCase.queryVector
      );
      expect(result.label).toBe(testCase.expected.label);
      expect(result.confidence).toBeCloseTo(testCase.expected.confidence, 4);
    }
  );
});

describe('the primitives the parity rests on', () => {
  it('normalizes whitespace the way Python does', () => {
    // Mirrors " ".join(text.lower().split()) — tabs, newlines and runs of
    // spaces all collapse, which is why the fixture includes a case with them.
    expect(normalizeText('  My   GPU\tDriver\n keeps   CRASHING  ')).toBe(
      'my gpu driver keeps crashing'
    );
  });

  it('encodes UTF-8 by hand, byte-for-byte with Python', () => {
    expect(utf8Bytes('a')).toEqual([0x61]);
    expect(utf8Bytes('é')).toEqual([0xc3, 0xa9]);
    // Outside the BMP: one code point, four bytes — the surrogate-pair case
    // that a naive charCodeAt loop gets wrong.
    expect(utf8Bytes('🙂')).toEqual([0xf0, 0x9f, 0x99, 0x82]);
  });

  it('hashes with FNV-1a exactly as the forge does', () => {
    // Published FNV-1a 32-bit vectors — independent of our implementation.
    expect(fnv1a(utf8Bytes(''))).toBe(0x811c9dc5);
    expect(fnv1a(utf8Bytes('a'))).toBe(0xe40c292c);
  });

  it('softmaxes to a distribution that sums to one', () => {
    const out = softmax([2, 1, 0.5]);
    expect(out.reduce((a, b) => a + b, 0)).toBeCloseTo(1, 10);
    expect(out[0]).toBeGreaterThan(out[1]);
  });

  it('stays stable on large scores rather than overflowing', () => {
    // Max-subtraction is why this does not become NaN.
    expect(softmax([1000, 999]).every(Number.isFinite)).toBe(true);
  });
});

describe('artifact validation', () => {
  it('accepts a real artifact from the fixture', () => {
    expect(() => validateArtifact(fixture.artifacts.nano)).not.toThrow();
  });

  it('rejects a file that is not a router artifact, with a usable message', () => {
    expect(() => validateArtifact({ hello: 'world' })).toThrow();
    expect(() => validateArtifact(null)).toThrow();
  });
});
